@isTest
public class TrailheadEntityUpdateEventTS extends TestSupport.DataGeneration {
    public TrailheadEntityUpdateEventTS(Map<String, Object> options) {
        super(options);
        this.S_OBJECT_TYPE = 'TrailheadEntityUpdateEvent__e';
    }

    public TrailheadEntityUpdateEventTS(Map<String, Object> options, List<TestSupport.TestDataField> fieldSpecs) {
        super(options, fieldSpecs);
        this.S_OBJECT_TYPE = 'TrailheadEntityUpdateEvent__e';
    }
}